function Hd = lowpass
%LOWPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
% Generated on: 21-Apr-2016 10:41:17

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 2500;  % Sampling Frequency

Fpass = 30;               % Passband Frequency
Fstop = 40;               % Stopband Frequency
Dpass = 0.0028782234183;  % Passband Ripple
Dstop = 0.0001;           % Stopband Attenuation
dens  = 20;               % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = b;

% [EOF]
